# Generated by Django 4.2.4 on 2023-09-22 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('event_type', models.CharField(blank=True, choices=[('boshlovchilar', 'Boshlovchilarga'), ('tajribalilar', 'Tajribalilarga'), ('barcha', 'Barcha uchun')], max_length=50)),
                ('event_datetime', models.DateTimeField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('places', models.CharField(blank=True, default='cheklanmagan', max_length=10)),
                ('about_event_short', models.TextField()),
                ('about_event_plain', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='speakers/')),
            ],
            options={
                'verbose_name_plural': 'Speakers',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('age', models.CharField(blank=True, max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_leads', to='events.event')),
            ],
            options={
                'verbose_name_plural': 'Leads',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='tag',
            field=models.ManyToManyField(related_name='tags', to='events.tag'),
        ),
    ]
