# Generated by Django 4.2.4 on 2023-09-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_card_image',
            field=models.ImageField(blank=True, upload_to='event_cover', verbose_name='380x480px'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_cover_image',
            field=models.ImageField(blank=True, upload_to='event_cover', verbose_name='1440x800px'),
        ),
    ]
